name: Checking package version drift
run-name: ${{ github.actor }} is ${{github.workflow}}

on:
  pull_request:
    branches: ["*"]

jobs:
  get-package-data-from-main:
    runs-on: ubuntu-latest
    outputs:
      MAIN_BRANCH_PACKAGE_VERSION: ${{ steps.packageVersion.outputs.packageVersion }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: run js file
        id: packageVersion
        run: node ./read-package-file.js
  get-package-data-from-merge-branch:
    runs-on: ubuntu-latest
    needs: get-package-data-from-main
    outputs:
      MERGE_BRANCH_PACKAGE_VERSION: ${{ steps.packageVersion.outputs.packageVersion }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: run js file
        id: packageVersion
        run: node ./read-package-file.js
  check-package-drift:
    needs: ["get-package-data-from-main", "get-package-data-from-merge-branch"]
    if: ${{ needs.get-package-data-from-main.outputs.MAIN_BRANCH_PACKAGE_VERSION == needs.get-package-data-from-merge-branch.outputs.MERGE_BRANCH_PACKAGE_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
