# Step 1 check out main and get that package file
# Step 2 save package version to output

name: Checking package version drift
run-name: ${{ github.actor }} is ${{github.workflow}}

on:
  pull_request:
    branches: ["*"]

jobs:
  get-data-from-main:
    runs-on: ubuntu-latest
    outputs:
        MAIN_BRANCH_PACKAGE_VERSION: ${{ steps.packageVersion.outputs.packageVersion }}
    steps:
      - uses: actions/checkout@v3
        # with:
        #     ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: run js file
        id: packageVersion
        run: node ./read-package-file.js
  read-output:
      runs-on: ubuntu-latest
      needs: get-data-from-main
      steps:
        - name: print output
          run: echo "${{needs.get-data-from-main.outputs.MAIN_BRANCH_PACKAGE_VERSION}}"
