name: Create Cron Schedule
run-name: ${{ github.actor }} ${{ github.workflow }}
# https://crontab.guru/

on: 
    schedule:
        - cron: '*/1 * * * *'

jobs:
    schedule:
        runs-on: ubuntu-latest
        steps:
            - name: run echo
              run: echo "Hello world"
            - name: get current time
              run:  echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')"