name: ignore push
run-name: ${{ github.actor }} is ${{github.workflow}}

on:
  push:
    branches: "*"

jobs:
  ignore-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
     - run: echo "not ignore main!"