name: Manual Web Scarping
run-name: ${{ github.actor }} ${{ github.workflow }}

on:
    workflow_dispatch:
jobs:
    collect-data:
      runs-on: ubuntu-latest
      steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Fetch latest data from the API endpoint
        run: |-
          curl -s "https://www.nu.nl/block/lean_json/articlelist?limit=20&offset=0&source=latest&filter=site" | jq '.data.context.articles' > headline/headlines.json
      - name: Commit and push if the data has changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push origin HEAD:main