name: Playwright Tests
run-name: ${{ github.actor }} is running Playwright test

on:
  # push:
  #   branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        BASEURL: "https://playwright.dev/"
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  publish-to-github-page:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Setup Page
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: playwright-report/
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1

