name: Create draft release note when merge main
on:
  pull_request:
    branches: 
      - main
    types: [opened]
permissions:
  contents: write
jobs:
  create-release-note:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get npm version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.package-version.outputs.current-version }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --generate-notes
