name: Create draft release note when merge main
run-name: ${{ github.actor }} ${{ github.workflow }}

on:
  workflow_dispatch:
  push:
    branches: 
      - main

permissions:
  contents: write

jobs:
  create-release-note:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get npm version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Get current month and year
        id: current-date
        run: |
          echo "::set-output name=current-date::$(date +'%b %Y')"
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.package-version.outputs.current-version }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="$current_date" \
            --generate-notes
