name: Run when merge main
run-name: ${{ github.actor }} ${{ github.workflow }}

on:
    pull_request:
      branches: 
        - main
      types: [closed]
jobs:
    action:
      if: ${{ github.event.pull_request.merged }}
      runs-on: ubuntu-latest
      steps:
        - run: echo "hello main"
  