name: Use Variable and Secret Key
run-name: ${{ github.actor }} ${{ github.workflow }}

on:
    push:

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: print Hello World
              run: echo "Hello World"
            - name: repository secret
              run: echo "${{secrets.REPO_SECRET}}"