name: Use Variable and Secret Key
run-name: ${{github.action_status}} ${{ github.actor }} ${{ github.workflow }} on ${{ github.env }}

on:
    push:

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: print Hello World
              run: echo "Hello World"